print('{:=^50}'.format('ANALISANDO UM NOME'))
nome = input('Digite seu nome completo: ').strip()
print('Seu nome em maiúscula é {}'.format(nome.upper()))
print('Seu nome em minúscula é {}'.format(nome.lower()))
print('O seu nome tem {} letras.'.format(len(nome) - nome.count(' ')))
nomesplit = nome.split()
#print('O seu nome tem {} letras.'.format(len(nome) - (len(nomesplit)-1)))
print('Seu nome tem {} letras'.format(nome.find(' ')))
print('E seu 1º nome é {} e tem {} letras.'.format(nomesplit[0], len(nomesplit[0])))