n = input('Digite uma informação: ')
print('O tipo primitivo desse valor é ',type(n))
print('É espaço?',n.isspace())
print('É númerico? {}'.format(n.isnumeric()))
print('É alfabético?',n.isalpha())
print('É alfa-numérico?', n.isalnum())
print('É decimal?', n.isdecimal())
print('É digit?', n.isdigit())
print('É identifier?', n.isidentifier())
print('É minúsculo?', n.islower())
print('É imprimível?', n.isprintable())
print('Está capitalizada?', n.istitle())
print('É maiúsculo?', n.isupper())
