frase = input('Escreva uma frase: ').strip()
print(len(frase))
print('A letra A aparece {} vezes'.format(frase.upper().count('A')))
print('A letra A aparece pela 1ª vez na posição {}'.format(frase.upper().find('A')+1))
print('A letra A aparece pela última vez na posição {}'.format(frase.upper().rfind('A')+1))
